apiVersion: v1
kind: Service
metadata:
  name: mern-fit-verse-clone
  labels:
    app: mern-fit-verse
spec:
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30003
  selector:
    app: mern-fit-verse

  type: NodePort